plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kaua.monitortermico'
    compileSdk 35

    defaultConfig {
        applicationId "com.kaua.monitortermico"
        minSdk 26
        targetSdk 35
        versionCode 9
        versionName "1.6.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    // Sem Shizuku e sem bibliotecas externas.
}
